version: '2'
services:
    bkfoodv3-app:
        image: bkfoodv3
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://bkfoodv3-mysql:3306/bkfoodv3?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bkfoodv3-mysql:
        extends:
            file: mysql.yml
            service: bkfoodv3-mysql
